# Generated by Django 3.0.4 on 2020-03-30 11:43

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        RunSQL("""
CREATE OR REPLACE TRIGGER trig_prevent_foo_question
    BEFORE DELETE
    ON polls_question
    FOR EACH ROW
BEGIN
        raise_application_error(-20001, 'Delete is not allowed.');
END;
/"""),            
    ]
